--viviendas

--a)renta
insert into vivienda (vivienda_id, longitud, latitud, capacidad_maxima, direccion, descripcion , es_renta, es_vaca, es_venta, fecha_status, usuario_id, status_vivienda_id) values (vivienda_seq.nextval, 17.3645179, 49.3564402, 65, '76117 Cottonwood Park', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst.Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', '1', '0', '0', to_date('16/06/2020', 'dd/mm/yyyy'), 72, 1);
insert into vivienda (vivienda_id, longitud, latitud, capacidad_maxima, direccion, descripcion , es_renta, es_vaca, es_venta, fecha_status, usuario_id, status_vivienda_id) values (vivienda_seq.nextval, 113.900628, 29.724692, 39, '8 Butterfield Road', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', '1', '0', '0', to_date('16/06/2020', 'dd/mm/yyyy'), 57, 1);
insert into vivienda (vivienda_id, longitud, latitud, capacidad_maxima, direccion, descripcion , es_renta, es_vaca, es_venta, fecha_status, usuario_id, status_vivienda_id) values (vivienda_seq.nextval, 131.0216903, 31.6546654, 17, '8 Marquette Alley', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', '1', '0', '0', to_date('16/06/2020', 'dd/mm/yyyy'), 37, 4);
insert into vivienda (vivienda_id, longitud, latitud, capacidad_maxima, direccion, descripcion , es_renta, es_vaca, es_venta, fecha_status, usuario_id, status_vivienda_id) values (vivienda_seq.nextval, 104.167501, 31.12678, 84, '49276 Express Plaza', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Integer non velit.', '1', '0', '0', to_date('16/06/2020', 'dd/mm/yyyy'), 25, 5);
insert into vivienda (vivienda_id, longitud, latitud, capacidad_maxima, direccion, descripcion , es_renta, es_vaca, es_venta, fecha_status, usuario_id, status_vivienda_id) values (vivienda_seq.nextval, 17.289051, 49.579879, 58, '5 Macpherson Junction', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus, pretium quis, lectus.', '1', '0', '0', to_date('16/06/2020', 'dd/mm/yyyy'), 45, 5);
insert into vivienda (vivienda_id, longitud, latitud, capacidad_maxima, direccion, descripcion , es_renta, es_vaca, es_venta, fecha_status, usuario_id, status_vivienda_id) values (vivienda_seq.nextval, 16.8799555, 52.3429156, 4, '03654 Basil Alley', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Fusce consequat. Nulla nisl. Nunc nisl.', '1', '0', '0', to_date('16/06/2020', 'dd/mm/yyyy'), 28, 6);
insert into vivienda (vivienda_id, longitud, latitud, capacidad_maxima, direccion, descripcion , es_renta, es_vaca, es_venta, fecha_status, usuario_id, status_vivienda_id) values (vivienda_seq.nextval, 33.3822764, 35.1855659, 9, '48480 Esker Circle', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', '1', '0', '0', to_date('16/06/2020', 'dd/mm/yyyy'), 74, 2);
insert into vivienda (vivienda_id, longitud, latitud, capacidad_maxima, direccion, descripcion , es_renta, es_vaca, es_venta, fecha_status, usuario_id, status_vivienda_id) values (vivienda_seq.nextval, 40.5343698, 56.1952581, 96, '926 Doe Crossing Alley', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', '1', '0', '0', to_date('16/06/2020', 'dd/mm/yyyy'), 1, 2);
insert into vivienda (vivienda_id, longitud, latitud, capacidad_maxima, direccion, descripcion , es_renta, es_vaca, es_venta, fecha_status, usuario_id, status_vivienda_id) values (vivienda_seq.nextval, -68.1247915, -38.9568843, 54, '04441 Bay Park', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', '1', '0', '0', to_date('16/06/2020', 'dd/mm/yyyy'), 51, 6);
insert into vivienda (vivienda_id, longitud, latitud, capacidad_maxima, direccion, descripcion , es_renta, es_vaca, es_venta, fecha_status, usuario_id, status_vivienda_id) values (vivienda_seq.nextval, 7.4165053, 10.5104642, 86, '9973 Mandrake Park', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', '1', '0', '0', to_date('16/06/2020', 'dd/mm/yyyy'), 33, 6);
insert into vivienda (vivienda_id, longitud, latitud, capacidad_maxima, direccion, descripcion , es_renta, es_vaca, es_venta, fecha_status, usuario_id, status_vivienda_id) values (vivienda_seq.nextval, 20.2599325, 63.827461, 69, '615 Mcguire Plaza', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', '1', '0', '0', to_date('16/06/2020', 'dd/mm/yyyy'), 100, 2);
insert into vivienda (vivienda_id, longitud, latitud, capacidad_maxima, direccion, descripcion , es_renta, es_vaca, es_venta, fecha_status, usuario_id, status_vivienda_id) values (vivienda_seq.nextval, 39.2331589, 55.6967262, 28, '370 Mayer Lane', 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', '1', '0', '0', to_date('16/06/2020', 'dd/mm/yyyy'), 85, 1);
insert into vivienda (vivienda_id, longitud, latitud, capacidad_maxima, direccion, descripcion , es_renta, es_vaca, es_venta, fecha_status, usuario_id, status_vivienda_id) values (vivienda_seq.nextval, -35.4210417, -5.6353028, 19, '42461 Northfield Circle', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', '1', '0', '0', to_date('16/06/2020', 'dd/mm/yyyy'), 98, 6);
insert into vivienda (vivienda_id, longitud, latitud, capacidad_maxima, direccion, descripcion , es_renta, es_vaca, es_venta, fecha_status, usuario_id, status_vivienda_id) values (vivienda_seq.nextval, 34.97298, 32.762127, 1, '183 Dottie Junction', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', '1', '0', '0', to_date('16/06/2020', 'dd/mm/yyyy'), 26, 3);
insert into vivienda (vivienda_id, longitud, latitud, capacidad_maxima, direccion, descripcion , es_renta, es_vaca, es_venta, fecha_status, usuario_id, status_vivienda_id) values (vivienda_seq.nextval, 35.7898106, -4.9068418, 73, '49294 Forest Alley', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', '1', '0', '0', to_date('16/06/2020', 'dd/mm/yyyy'), 69, 1);
insert into vivienda (vivienda_id, longitud, latitud, capacidad_maxima, direccion, descripcion , es_renta, es_vaca, es_venta, fecha_status, usuario_id, status_vivienda_id) values (vivienda_seq.nextval, -43.599128, -22.4028163, 63, '2 Sheridan Trail', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', '1', '0', '0', to_date('16/06/2020', 'dd/mm/yyyy'), 22, 5);
insert into vivienda (vivienda_id, longitud, latitud, capacidad_maxima, direccion, descripcion , es_renta, es_vaca, es_venta, fecha_status, usuario_id, status_vivienda_id) values (vivienda_seq.nextval, 32.3522621, 46.3601437, 67, '7 Bowman Terrace', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', '1', '0', '0', to_date('16/06/2020', 'dd/mm/yyyy'), 6, 2);
insert into vivienda (vivienda_id, longitud, latitud, capacidad_maxima, direccion, descripcion , es_renta, es_vaca, es_venta, fecha_status, usuario_id, status_vivienda_id) values (vivienda_seq.nextval, 122.0185, 30.051035, 77, '62 Shopko Park', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', '1', '0', '0', to_date('16/06/2020', 'dd/mm/yyyy'), 29, 6);
insert into vivienda (vivienda_id, longitud, latitud, capacidad_maxima, direccion, descripcion , es_renta, es_vaca, es_venta, fecha_status, usuario_id, status_vivienda_id) values (vivienda_seq.nextval, -100.2602364, 25.6765837, 18, '0218 Ludington Plaza', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', '1', '0', '0', to_date('16/06/2020', 'dd/mm/yyyy'), 7, 3);
insert into vivienda (vivienda_id, longitud, latitud, capacidad_maxima, direccion, descripcion , es_renta, es_vaca, es_venta, fecha_status, usuario_id, status_vivienda_id) values (vivienda_seq.nextval, 112.7986343, -7.3949134, 77, '98 Grover Place', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', '1', '0', '0', to_date('16/06/2020', 'dd/mm/yyyy'), 38, 3);


--b)vaca

insert into vivienda (vivienda_id, longitud, latitud, capacidad_maxima, direccion, descripcion , es_renta, es_vaca, es_venta, fecha_status, usuario_id, status_vivienda_id) values (vivienda_seq.nextval, 114.720925, 30.352134, 23, '3 Sloan Street', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', '0', '1', '0', to_date('16/06/2020', 'dd/mm/yyyy'), 16, 5);
insert into vivienda (vivienda_id, longitud, latitud, capacidad_maxima, direccion, descripcion , es_renta, es_vaca, es_venta, fecha_status, usuario_id, status_vivienda_id) values (vivienda_seq.nextval, 139.7874841, 37.4056028, 2, '540 Parkside Trail', 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', '0', '1', '0', to_date('16/06/2020', 'dd/mm/yyyy'), 24, 3);
insert into vivienda (vivienda_id, longitud, latitud, capacidad_maxima, direccion, descripcion , es_renta, es_vaca, es_venta, fecha_status, usuario_id, status_vivienda_id) values (vivienda_seq.nextval, 43.6369585, 44.2643449, 95, '558 Spohn Avenue', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', '0', '1', '0', to_date('16/06/2020', 'dd/mm/yyyy'), 86, 3);
insert into vivienda (vivienda_id, longitud, latitud, capacidad_maxima, direccion, descripcion , es_renta, es_vaca, es_venta, fecha_status, usuario_id, status_vivienda_id) values (vivienda_seq.nextval, 67.7079491, 36.7027082, 98, '72619 Roxbury Circle', 'Phasellus in felis. Donec semper sapien a libero. Nam dui.Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', '0', '1', '0', to_date('16/06/2020', 'dd/mm/yyyy'), 99, 1);
insert into vivienda (vivienda_id, longitud, latitud, capacidad_maxima, direccion, descripcion , es_renta, es_vaca, es_venta, fecha_status, usuario_id, status_vivienda_id) values (vivienda_seq.nextval, 110.7867474, -7.5519782, 5, '998 Upham Center', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', '0', '1', '0', to_date('16/06/2020', 'dd/mm/yyyy'), 92, 1);
insert into vivienda (vivienda_id, longitud, latitud, capacidad_maxima, direccion, descripcion , es_renta, es_vaca, es_venta, fecha_status, usuario_id, status_vivienda_id) values (vivienda_seq.nextval, 110.7167165, -7.6155876, 94, '2 Ryan Junction', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', '0', '1', '0', to_date('16/06/2020', 'dd/mm/yyyy'), 83, 3);
insert into vivienda (vivienda_id, longitud, latitud, capacidad_maxima, direccion, descripcion , es_renta, es_vaca, es_venta, fecha_status, usuario_id, status_vivienda_id) values (vivienda_seq.nextval, -100.2596935, 25.6775595, 29, '609 Grover Point', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', '0', '1', '0', to_date('16/06/2020', 'dd/mm/yyyy'), 18, 6);
insert into vivienda (vivienda_id, longitud, latitud, capacidad_maxima, direccion, descripcion , es_renta, es_vaca, es_venta, fecha_status, usuario_id, status_vivienda_id) values (vivienda_seq.nextval, 113.8526, -8.0299, 37, '24 Lyons Center', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', '0', '1', '0', to_date('16/06/2020', 'dd/mm/yyyy'), 31, 1);
insert into vivienda (vivienda_id, longitud, latitud, capacidad_maxima, direccion, descripcion , es_renta, es_vaca, es_venta, fecha_status, usuario_id, status_vivienda_id) values (vivienda_seq.nextval, 73.2498639, 55.0614182, 72, '37 Prentice Lane', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', '0', '1', '0', to_date('16/06/2020', 'dd/mm/yyyy'), 60, 2);
insert into vivienda (vivienda_id, longitud, latitud, capacidad_maxima, direccion, descripcion , es_renta, es_vaca, es_venta, fecha_status, usuario_id, status_vivienda_id) values (vivienda_seq.nextval, -13.2317225, 8.4656765, 4, '1 Gulseth Center', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', '0', '1', '0', to_date('16/06/2020', 'dd/mm/yyyy'), 53, 1);

--
insert into vivienda (vivienda_id, longitud, latitud, capacidad_maxima, direccion, descripcion , es_renta, es_vaca, es_venta, fecha_status, usuario_id, status_vivienda_id) values (vivienda_seq.nextval, 121.6482773, 18.1605511, 28, '95 Cherokee Junction', 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', '1', '1', '0', to_date('16/06/2020', 'dd/mm/yyyy'), 32, 3);
insert into vivienda (vivienda_id, longitud, latitud, capacidad_maxima, direccion, descripcion , es_renta, es_vaca, es_venta, fecha_status, usuario_id, status_vivienda_id) values (vivienda_seq.nextval, 19.5627596, 41.1844529, 88, '3 Welch Park', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', '1', '1', '0', to_date('16/06/2020', 'dd/mm/yyyy'), 68, 4);
insert into vivienda (vivienda_id, longitud, latitud, capacidad_maxima, direccion, descripcion , es_renta, es_vaca, es_venta, fecha_status, usuario_id, status_vivienda_id) values (vivienda_seq.nextval, 36.08677, 35.07437, 32, '29420 East Point', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', '1', '1', '0', to_date('16/06/2020', 'dd/mm/yyyy'), 7, 5);
insert into vivienda (vivienda_id, longitud, latitud, capacidad_maxima, direccion, descripcion , es_renta, es_vaca, es_venta, fecha_status, usuario_id, status_vivienda_id) values (vivienda_seq.nextval, 24.2503492, 53.5866599, 36, '404 Loomis Point', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', '1', '1', '0', to_date('16/06/2020', 'dd/mm/yyyy'), 60, 4);
insert into vivienda (vivienda_id, longitud, latitud, capacidad_maxima, direccion, descripcion , es_renta, es_vaca, es_venta, fecha_status, usuario_id, status_vivienda_id) values (vivienda_seq.nextval, 114.3110482, 30.6074358, 93, '87 Utah Plaza', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', '1', '1', '0', to_date('16/06/2020', 'dd/mm/yyyy'), 98, 6);
insert into vivienda (vivienda_id, longitud, latitud, capacidad_maxima, direccion, descripcion , es_renta, es_vaca, es_venta, fecha_status, usuario_id, status_vivienda_id) values (vivienda_seq.nextval, -73.6760258, -13.5321991, 46, '86 Nobel Terrace', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', '1', '1', '0', to_date('16/06/2020', 'dd/mm/yyyy'), 35, 2);
insert into vivienda (vivienda_id, longitud, latitud, capacidad_maxima, direccion, descripcion , es_renta, es_vaca, es_venta, fecha_status, usuario_id, status_vivienda_id) values (vivienda_seq.nextval, 124.6005108, 11.1300808, 30, '400 Del Mar Lane', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', '1', '1', '0', to_date('16/06/2020', 'dd/mm/yyyy'), 73, 2);
insert into vivienda (vivienda_id, longitud, latitud, capacidad_maxima, direccion, descripcion , es_renta, es_vaca, es_venta, fecha_status, usuario_id, status_vivienda_id) values (vivienda_seq.nextval, -1.1547612, 50.6538116, 22, '615 Dryden Center', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', '1', '1', '0', to_date('16/06/2020', 'dd/mm/yyyy'), 78, 6);
insert into vivienda (vivienda_id, longitud, latitud, capacidad_maxima, direccion, descripcion , es_renta, es_vaca, es_venta, fecha_status, usuario_id, status_vivienda_id) values (vivienda_seq.nextval, -90.2291565, 38.6160491, 42, '9 Jay Road', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', '1', '1', '0', to_date('16/06/2020', 'dd/mm/yyyy'), 90, 6);
insert into vivienda (vivienda_id, longitud, latitud, capacidad_maxima, direccion, descripcion , es_renta, es_vaca, es_venta, fecha_status, usuario_id, status_vivienda_id) values (vivienda_seq.nextval, -73.0405277, 11.3421375, 35, '35195 Melrose Trail', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', '1', '1', '0', to_date('16/06/2020', 'dd/mm/yyyy'), 27, 5);


--c)venta

insert into vivienda (vivienda_id, longitud, latitud, capacidad_maxima, direccion, descripcion , es_renta, es_vaca, es_venta, fecha_status, usuario_id, status_vivienda_id) values (vivienda_seq.nextval, -60.6923382, -32.9285798, 68, '822 Dorton Way', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', '0', '0', '1', to_date('16/06/2020', 'dd/mm/yyyy'), 73, 4);
insert into vivienda (vivienda_id, longitud, latitud, capacidad_maxima, direccion, descripcion , es_renta, es_vaca, es_venta, fecha_status, usuario_id, status_vivienda_id) values (vivienda_seq.nextval, 30.9531791, 30.9765009, 62, '71 Cottonwood Park', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', '0', '0', '1', to_date('16/06/2020', 'dd/mm/yyyy'), 70, 6);
insert into vivienda (vivienda_id, longitud, latitud, capacidad_maxima, direccion, descripcion , es_renta, es_vaca, es_venta, fecha_status, usuario_id, status_vivienda_id) values (vivienda_seq.nextval, 136.0396342, -1.145463, 46, '43 Florence Crossing', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', '0', '0', '1', to_date('16/06/2020', 'dd/mm/yyyy'), 3, 6);
insert into vivienda (vivienda_id, longitud, latitud, capacidad_maxima, direccion, descripcion , es_renta, es_vaca, es_venta, fecha_status, usuario_id, status_vivienda_id) values (vivienda_seq.nextval, 24.8715019, 43.4650355, 14, '57760 Raven Parkway', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', '0', '0', '1', to_date('16/06/2020', 'dd/mm/yyyy'), 30, 2);
insert into vivienda (vivienda_id, longitud, latitud, capacidad_maxima, direccion, descripcion , es_renta, es_vaca, es_venta, fecha_status, usuario_id, status_vivienda_id) values (vivienda_seq.nextval, 16.0917932, 43.0444596, 15, '011 Dunning Way', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', '0', '0', '1', to_date('16/06/2020', 'dd/mm/yyyy'), 73, 1);
insert into vivienda (vivienda_id, longitud, latitud, capacidad_maxima, direccion, descripcion , es_renta, es_vaca, es_venta, fecha_status, usuario_id, status_vivienda_id) values (vivienda_seq.nextval, 124.5351538, 40.1976461, 79, '7 Crest Line Terrace', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', '0', '0', '1', to_date('16/06/2020', 'dd/mm/yyyy'), 19, 6);
insert into vivienda (vivienda_id, longitud, latitud, capacidad_maxima, direccion, descripcion , es_renta, es_vaca, es_venta, fecha_status, usuario_id, status_vivienda_id) values (vivienda_seq.nextval, 119.775799, 39.978848, 95, '7188 Almo Way', 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', '0', '0', '1', to_date('16/06/2020', 'dd/mm/yyyy'), 23, 1);
insert into vivienda (vivienda_id, longitud, latitud, capacidad_maxima, direccion, descripcion , es_renta, es_vaca, es_venta, fecha_status, usuario_id, status_vivienda_id) values (vivienda_seq.nextval, 113.300129, 40.076762, 2, '20 Scott Road', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', '0', '0', '1', to_date('16/06/2020', 'dd/mm/yyyy'), 88, 6);
insert into vivienda (vivienda_id, longitud, latitud, capacidad_maxima, direccion, descripcion , es_renta, es_vaca, es_venta, fecha_status, usuario_id, status_vivienda_id) values (vivienda_seq.nextval, 100.4547262, -0.9233715, 88, '63 Park Meadow Pass', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', '0', '0', '1', to_date('16/06/2020', 'dd/mm/yyyy'), 42, 1);
insert into vivienda (vivienda_id, longitud, latitud, capacidad_maxima, direccion, descripcion , es_renta, es_vaca, es_venta, fecha_status, usuario_id, status_vivienda_id) values (vivienda_seq.nextval, 112.4917291, -6.9556847, 51, '3994 Blackbird Hill', 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', '0', '0', '1', to_date('16/06/2020', 'dd/mm/yyyy'), 15, 4);


prompt VIVIENDAS

